@tool
extends EditorPlugin

func _enter_tree() -> void:
	add_custom_type("BoundToViewportComponent", "Node", preload("components/bound-to-viewport/BoundToViewportComponent.gd"), null)
	add_custom_type("BulletComponent", "Node", preload("components/bullet/BulletComponent.gd"), null)
	add_custom_type("Camera2DComponent", "Camera2D", preload("components/camera/Camera2DComponent.gd"), null)
	add_custom_type("CarComponent", "Node2D", preload("components/car/CarComponent.gd"), null)
	add_custom_type("ColoredCollisionShape2D", "CollisionShape2D", preload("components/colored-collision-shape-2d/ColoredCollisionShape2D.gd"), null)
	add_custom_type("DetectorComponent", "Area2D", preload("components/detector/DetectorComponent.gd"), null)
	add_custom_type("FlashComponent", "Node", preload("components/flash/FlashComponent.gd"), null)
	add_custom_type("GamepadDebuggerComponent", "Control", preload("components/gamepad-debugger/GamepadDebuggerComponent.gd"), null)
	add_custom_type("HealthComponent", "Node", preload("components/health/HealthComponent.gd"), null)
	add_custom_type("HitboxComponent", "Area2D", preload("components/hitbox/HitboxComponent.gd"), null)
	add_custom_type("HurtboxComponent", "Area2D", preload("components/hurtbox/HurtboxComponent.gd"), null)
	add_custom_type("KnockbackComponent", "Node", preload("components/knockback/KnockbackComponent.gd"), null)
	add_custom_type("LookAtComponent", "Node2D", preload("components/look-at/LookAtComponent.gd"), null)
	add_custom_type("OrbitComponent", "Node", preload("components/orbit/OrbitComponent.gd"), null)
	add_custom_type("PlatformerComponent", "Node", preload("components/platformer/PlatformerComponent.gd"), null)
	add_custom_type("PlayerInputComponent", "Node", preload("components/player-input/PlayerInputComponent.gd"), null)
	add_custom_type("PriorityQueue", "Object", preload("components/priority-queue/PriorityQueue.gd"), null)
	add_custom_type("RandomTimer", "Timer", preload("components/random-timer/RandomTimer.gd"), null)
	add_custom_type("ReplaceColorComponent", "Node", preload("components/replace-color/ReplaceColorComponent.gd"), null)
	add_custom_type("RotateComponent", "Node", preload("components/rotate/RotateComponent.gd"), null)
	add_custom_type("SquashAndStretchComponent", "Node", preload("components/squash-and-stretch/SquashAndStretchComponent.gd"), null)
	add_custom_type("StateMachine", "Node", preload("components/state-machine/StateMachine.gd"), null)
	add_custom_type("TileMovementComponent", "Node2D", preload("components/tile-movement/TileMovementComponent.gd"), null)
	add_custom_type("UIComponent", "Control", preload("components/ui/UIComponent.gd"), null)
	add_custom_type("VelocityComponent", "Node", preload("components/velocity/VelocityComponent.gd"), null)
	add_custom_type("WeightedChoiceComponent", "Node", preload("components/weighted-choice/WeightedChoiceComponent.gd"), null)

func _exit_tree() -> void:
	remove_custom_type("BoundToViewportComponent")
	remove_custom_type("BulletComponent")
	remove_custom_type("Camera2DComponent")
	remove_custom_type("CarComponent")
	remove_custom_type("ColoredCollisionShape2D")
	remove_custom_type("DetectorComponent")
	remove_custom_type("FlashComponent")
	remove_custom_type("GamepadDebuggerComponent")
	remove_custom_type("HealthComponent")
	remove_custom_type("HitboxComponent")
	remove_custom_type("HurtboxComponent")
	remove_custom_type("KnockbackComponent")
	remove_custom_type("LookAtComponent")
	remove_custom_type("OrbitComponent")
	remove_custom_type("PlatformerComponent")
	remove_custom_type("PlayerInputComponent")
	remove_custom_type("PriorityQueue")
	remove_custom_type("RandomTimer")
	remove_custom_type("ReplaceColorComponent")
	remove_custom_type("RotateComponent")
	remove_custom_type("SquashAndStretchComponent")
	remove_custom_type("StateMachine")
	remove_custom_type("TileMovementComponent")
	remove_custom_type("UIComponent")
	remove_custom_type("VelocityComponent")
	remove_custom_type("WeightedChoiceComponent")
